import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const sourceCodePro = Source_Code_Pro({
  subsets: ["latin"],
  variable: "--font-source-code-pro",
  weight: ["400", "700"],
});

const circulatStdBook = localFont({
  src: "./fonts/CircularStd-Book.woff",
  variable: "--font-cir-std-book",
  weight: "100 400 800",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sourceCodePro.variable} ${circulatStdBook.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
